// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// internal/adapters/inbound/http/web/templates/components/layout/app_brand.templ

package layoutcomponents

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AppBrand() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<a class=\"flex items-center gap-2 font-semibold tracking-tight text-on-surface hover:text-primary\" href=\"/\"><span class=\"inline-flex size-8 items-center justify-center rounded-lg bg-tertiary text-on-primary\"><svg class=\"size-4\" viewBox=\"0 0 24 24\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M12 3.3L5 6v6.41c0 2.9 1.86 5.58 4.66 6.62l1.84.69c.33.12.68.12 1.01 0l1.83-.69A7.23 7.23 0 0 0 19 12.41V6l-7-2.7Zm0 1.16 6 2.31v5.64a6.07 6.07 0 0 1-3.9 5.63l-1.65.62a.3.3 0 0 1-.2 0l-1.66-.62A6.07 6.07 0 0 1 6 12.41V6.77l6-2.3Zm0 2.97-4 1.54v3.14c0 2 .92 3.92 2.48 5.17l1.15.93c.22.18.53.18.75 0l1.15-.93A6.69 6.69 0 0 0 16 12.11V8.97l-4-1.54Z\"></path></svg></span> <span class=\"text-base sm:text-lg text-white\">Sonnda</span></a>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
