// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package userssqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppUser struct {
	ID           pgtype.UUID        `json:"id"`
	AuthProvider string             `json:"auth_provider"`
	AuthSubject  pgtype.UUID        `json:"auth_subject"`
	Email        string             `json:"email"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
