// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package userssqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO app_users (auth_provider, auth_subject, email, role)
VALUES ($1, $2, $3, $4)
RETURNING
    id,
    auth_provider,
    auth_subject,
    email,
    role,
    created_at,
    updated_at
`

type CreateUserParams struct {
	AuthProvider string `json:"auth_provider"`
	AuthSubject  string `json:"auth_subject"`
	Email        string `json:"email"`
	Role         string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.AuthProvider,
		arg.AuthSubject,
		arg.Email,
		arg.Role,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByAuthIdentity = `-- name: FindUserByAuthIdentity :one

SELECT
    id,
    auth_provider,
    auth_subject,
    email,
    role,
    created_at,
    updated_at
FROM app_users
WHERE auth_provider = $1
  AND auth_subject = $2
`

type FindUserByAuthIdentityParams struct {
	AuthProvider string `json:"auth_provider"`
	AuthSubject  string `json:"auth_subject"`
}

// internal/adapters/outbound/database/sqlc/users/queries.sql
func (q *Queries) FindUserByAuthIdentity(ctx context.Context, arg FindUserByAuthIdentityParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, findUserByAuthIdentity, arg.AuthProvider, arg.AuthSubject)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT
    id,
    auth_provider,
    auth_subject,
    email,
    role,
    created_at,
    updated_at
FROM app_users
WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (AppUser, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT
    id,
    auth_provider,
    auth_subject,
    email,
    role,
    created_at,
    updated_at
FROM app_users
WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (AppUser, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserAuthIdentity = `-- name: UpdateUserAuthIdentity :one
UPDATE app_users
SET auth_provider = $1,
    auth_subject  = $2,
    updated_at    = now()
WHERE id = $3
RETURNING
    id,
    auth_provider,
    auth_subject,
    email,
    role,
    created_at,
    updated_at
`

type UpdateUserAuthIdentityParams struct {
	AuthProvider string      `json:"auth_provider"`
	AuthSubject  string      `json:"auth_subject"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserAuthIdentity(ctx context.Context, arg UpdateUserAuthIdentityParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, updateUserAuthIdentity, arg.AuthProvider, arg.AuthSubject, arg.ID)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
