// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package patientssqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Patient struct {
	ID        pgtype.UUID        `json:"id"`
	AppUserID pgtype.UUID        `json:"app_user_id"`
	Cpf       string             `json:"cpf"`
	Cns       pgtype.Text        `json:"cns"`
	FullName  string             `json:"full_name"`
	BirthDate pgtype.Date        `json:"birth_date"`
	Gender    string             `json:"gender"`
	Race      string             `json:"race"`
	Phone     pgtype.Text        `json:"phone"`
	AvatarUrl string             `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
