// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package patientssqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPatient = `-- name: CreatePatient :one


INSERT INTO patients (
    id,
    app_user_id,
    cpf,
    cns,
    full_name,
    birth_date,
    gender,
    race,
    phone,
    avatar_url
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING
    id,
    app_user_id,
    cpf,
    cns,
    full_name,
    birth_date,
    gender,
    race,
    phone,
    avatar_url,
    created_at,
    updated_at
`

type CreatePatientParams struct {
	ID        string      `json:"id"`
	AppUserID pgtype.Text `json:"app_user_id"`
	Cpf       string      `json:"cpf"`
	Cns       pgtype.Text `json:"cns"`
	FullName  string      `json:"full_name"`
	BirthDate pgtype.Date `json:"birth_date"`
	Gender    string      `json:"gender"`
	Race      string      `json:"race"`
	Phone     pgtype.Text `json:"phone"`
	AvatarUrl string      `json:"avatar_url"`
}

// internal/adapters/outbound/database/sqlc/patients/queries.sql
// Common column set for patient fetches:
// id, app_user_id, cpf, cns, full_name, birth_date, gender, race, phone, avatar_url, created_at, updated_at
func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.ID,
		arg.AppUserID,
		arg.Cpf,
		arg.Cns,
		arg.FullName,
		arg.BirthDate,
		arg.Gender,
		arg.Race,
		arg.Phone,
		arg.AvatarUrl,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.AppUserID,
		&i.Cpf,
		&i.Cns,
		&i.FullName,
		&i.BirthDate,
		&i.Gender,
		&i.Race,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePatient = `-- name: DeletePatient :execrows
DELETE FROM patients WHERE id = $1
`

func (q *Queries) DeletePatient(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePatient, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findPatientByCPF = `-- name: FindPatientByCPF :one
SELECT
    id,
    app_user_id,
    cpf,
    cns,
    full_name,
    birth_date,
    gender,
    race,
    phone,
    avatar_url,
    created_at,
    updated_at
FROM patients
WHERE cpf = $1
LIMIT 1
`

func (q *Queries) FindPatientByCPF(ctx context.Context, cpf string) (Patient, error) {
	row := q.db.QueryRow(ctx, findPatientByCPF, cpf)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.AppUserID,
		&i.Cpf,
		&i.Cns,
		&i.FullName,
		&i.BirthDate,
		&i.Gender,
		&i.Race,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPatientByID = `-- name: FindPatientByID :one
SELECT
    id,
    app_user_id,
    cpf,
    cns,
    full_name,
    birth_date,
    gender,
    race,
    phone,
    avatar_url,
    created_at,
    updated_at
FROM patients
WHERE id = $1
LIMIT 1
`

func (q *Queries) FindPatientByID(ctx context.Context, id string) (Patient, error) {
	row := q.db.QueryRow(ctx, findPatientByID, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.AppUserID,
		&i.Cpf,
		&i.Cns,
		&i.FullName,
		&i.BirthDate,
		&i.Gender,
		&i.Race,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPatientByUserID = `-- name: FindPatientByUserID :one
SELECT
    id,
    app_user_id,
    cpf,
    cns,
    full_name,
    birth_date,
    gender,
    race,
    phone,
    avatar_url,
    created_at,
    updated_at
FROM patients
WHERE app_user_id = $1
LIMIT 1
`

func (q *Queries) FindPatientByUserID(ctx context.Context, appUserID pgtype.Text) (Patient, error) {
	row := q.db.QueryRow(ctx, findPatientByUserID, appUserID)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.AppUserID,
		&i.Cpf,
		&i.Cns,
		&i.FullName,
		&i.BirthDate,
		&i.Gender,
		&i.Race,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPatients = `-- name: ListPatients :many
SELECT
    id,
    app_user_id,
    cpf,
    cns,
    full_name,
    birth_date,
    gender,
    race,
    phone,
    avatar_url,
    created_at,
    updated_at
FROM patients
ORDER BY full_name ASC
LIMIT $1 OFFSET $2
`

type ListPatientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPatients(ctx context.Context, arg ListPatientsParams) ([]Patient, error) {
	rows, err := q.db.Query(ctx, listPatients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Patient
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.AppUserID,
			&i.Cpf,
			&i.Cns,
			&i.FullName,
			&i.BirthDate,
			&i.Gender,
			&i.Race,
			&i.Phone,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatient = `-- name: UpdatePatient :one
UPDATE patients
SET cpf        = $2,
    cns        = $3,
    full_name  = $4,
    birth_date = $5,
    gender     = $6,
    race       = $7,
    phone      = $8,
    avatar_url = $9,
    updated_at = now()
WHERE id = $1
RETURNING
    id,
    app_user_id,
    cpf,
    cns,
    full_name,
    birth_date,
    gender,
    race,
    phone,
    avatar_url,
    created_at,
    updated_at
`

type UpdatePatientParams struct {
	ID        string      `json:"id"`
	Cpf       string      `json:"cpf"`
	Cns       pgtype.Text `json:"cns"`
	FullName  string      `json:"full_name"`
	BirthDate pgtype.Date `json:"birth_date"`
	Gender    string      `json:"gender"`
	Race      string      `json:"race"`
	Phone     pgtype.Text `json:"phone"`
	AvatarUrl string      `json:"avatar_url"`
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, updatePatient,
		arg.ID,
		arg.Cpf,
		arg.Cns,
		arg.FullName,
		arg.BirthDate,
		arg.Gender,
		arg.Race,
		arg.Phone,
		arg.AvatarUrl,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.AppUserID,
		&i.Cpf,
		&i.Cns,
		&i.FullName,
		&i.BirthDate,
		&i.Gender,
		&i.Race,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
