// internal/kernel/apperr/catalog.go
package apperr

type ErrorCode string

const (
	//AUTHENTICATION
	AUTH_REQUIRED      ErrorCode = "AUTH_REQUIRED"
	AUTH_TOKEN_INVALID ErrorCode = "AUTH_TOKEN_INVALID"
	AUTH_TOKEN_EXPIRED ErrorCode = "AUTH_TOKEN_EXPIRED"
	//AUTHORIZATION
	ACCESS_DENIED      ErrorCode = "ACCESS_DENIED"
	ACTION_NOT_ALLOWED ErrorCode = "ACTION_NOT_ALLOWED"
	//VALIDATION
	VALIDATION_FAILED      ErrorCode = "VALIDATION_FAILED"
	REQUIRED_FIELD_MISSING ErrorCode = "REQUIRED_FIELD_MISSING"
	INVALID_FIELD_FORMAT   ErrorCode = "INVALID_FIELD_FORMAT"
	INVALID_ENUM_VALUE     ErrorCode = "INVALID_ENUM_VALUE"
	INVALID_DATE           ErrorCode = "INVALID_DATE"
	//NOT FOUND (DEPOIS PODEM EXISTIR NOT_FOUND ESPECÍFICOS)
	NOT_FOUND ErrorCode = "NOT_FOUND"
	//CONFLICT
	RESOURCE_CONFLICT       ErrorCode = "RESOURCE_CONFLICT"
	RESOURCE_ALREADY_EXISTS ErrorCode = "RESOURCE_ALREADY_EXISTS"
	//DOMAIN
	DOMAIN_RULE_VIOLATION ErrorCode = "DOMAIN_RULE_VIOLATION"
	//INFRA
	INFRA_AUTHENTICATION_ERROR   ErrorCode = "INFRA_AUTHENTICATION_ERROR"
	INFRA_DATABASE_ERROR         ErrorCode = "INFRA_DATABASE_ERROR"
	INFRA_STORAGE_ERROR          ErrorCode = "INFRA_STORAGE_ERROR"
	INFRA_EXTERNAL_SERVICE_ERROR ErrorCode = "INFRA_EXTERNAL_SERVICE_ERROR"
	INFRA_TIMEOUT                ErrorCode = "INFRA_TIMEOUT"
	//RATE
	RATE_LIMIT_EXCEEDED  ErrorCode = "RATE_LIMIT_EXCEEDED"
	UPLOAD_SIZE_EXCEEDED ErrorCode = "UPLOAD_SIZE_EXCEEDED"
	//INTERNAL
	INTERNAL_ERROR ErrorCode = "INTERNAL_ERROR"
)
