// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package labssqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LabReport struct {
	ID                string             `json:"id"`
	PatientID         string             `json:"patient_id"`
	PatientName       pgtype.Text        `json:"patient_name"`
	PatientDob        pgtype.Date        `json:"patient_dob"`
	LabName           pgtype.Text        `json:"lab_name"`
	LabPhone          pgtype.Text        `json:"lab_phone"`
	InsuranceProvider pgtype.Text        `json:"insurance_provider"`
	RequestingDoctor  pgtype.Text        `json:"requesting_doctor"`
	TechnicalManager  pgtype.Text        `json:"technical_manager"`
	ReportDate        pgtype.Date        `json:"report_date"`
	RawText           pgtype.Text        `json:"raw_text"`
	UploadedByUserID  pgtype.Text        `json:"uploaded_by_user_id"`
	Fingerprint       pgtype.Text        `json:"fingerprint"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type LabResult struct {
	ID          string             `json:"id"`
	LabReportID string             `json:"lab_report_id"`
	TestName    string             `json:"test_name"`
	Material    pgtype.Text        `json:"material"`
	Method      pgtype.Text        `json:"method"`
	CollectedAt pgtype.Timestamptz `json:"collected_at"`
	ReleaseAt   pgtype.Timestamptz `json:"release_at"`
}

type LabResultItem struct {
	ID            string      `json:"id"`
	LabResultID   string      `json:"lab_result_id"`
	ParameterName string      `json:"parameter_name"`
	ResultValue   pgtype.Text `json:"result_value"`
	ResultUnit    pgtype.Text `json:"result_unit"`
	ReferenceText pgtype.Text `json:"reference_text"`
}
