// internal/app/apperr/catalog.go
package apperr

type ErrorCode string

const (
	//AUTH
	AUTH_REQUIRED      ErrorCode = "AUTH_REQUIRED"      //401
	AUTH_TOKEN_INVALID ErrorCode = "AUTH_TOKEN_INVALID" //401
	AUTH_TOKEN_EXPIRED ErrorCode = "AUTH_TOKEN_EXPIRED" //401
	//AUTHZ
	ACCESS_DENIED      ErrorCode = "ACCESS_DENIED"      //403
	ACTION_NOT_ALLOWED ErrorCode = "ACTION_NOT_ALLOWED" //403
	//VALIDATION
	VALIDATION_FAILED      ErrorCode = "VALIDATION_FAILED"      //400
	REQUIRED_FIELD_MISSING ErrorCode = "REQUIRED_FIELD_MISSING" //400
	INVALID_FIELD_FORMAT   ErrorCode = "INVALID_FIELD_FORMAT"   //400
	INVALID_ENUM_VALUE     ErrorCode = "INVALID_ENUM_VALUE"     //400
	INVALID_DATE           ErrorCode = "INVALID_DATE"           //400
	//NOT FOUND
	NOT_FOUND ErrorCode = "NOT_FOUND" //404
	//CONFLICT
	RESOURCE_CONFLICT       ErrorCode = "RESOURCE_CONFLICT"       //409
	RESOURCE_ALREADY_EXISTS ErrorCode = "RESOURCE_ALREADY_EXISTS" //409
	//DOMAIN
	DOMAIN_RULE_VIOLATION ErrorCode = "DOMAIN_RULE_VIOLATION" //422
	//INFRA
	INFRA_AUTHENTICATION_ERROR   ErrorCode = "INFRA_AUTHENTICATION_ERROR"   //500
	INFRA_DATABASE_ERROR         ErrorCode = "INFRA_DATABASE_ERROR"         //500
	INFRA_STORAGE_ERROR          ErrorCode = "INFRA_STORAGE_ERROR"          //500
	INFRA_EXTERNAL_SERVICE_ERROR ErrorCode = "INFRA_EXTERNAL_SERVICE_ERROR" //502
	INFRA_TIMEOUT                ErrorCode = "INFRA_TIMEOUT"                //504
	//RATE
	RATE_LIMIT_EXCEEDED  ErrorCode = "RATE_LIMIT_EXCEEDED"  //429
	UPLOAD_SIZE_EXCEEDED ErrorCode = "UPLOAD_SIZE_EXCEEDED" //413
	//INTERNAL
	INTERNAL_ERROR ErrorCode = "INTERNAL_ERROR" //500

)
