// cmd/openapi-embed/main.go
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"

	openapitools "github.com/gabrielgcmr/sonnda/internal/tooling/openapi"
)

func main() {
	inputPath := flag.String("input", "openapi.yaml", "path to the OpenAPI source file")
	outputPath := flag.String("output", "openapi_spec_gen.go", "path to the generated Go file")
	flag.Parse()

	data, err := openapitools.Bundle(*inputPath)
	if err != nil {
		fail("read OpenAPI source", err)
	}

	content := fmt.Sprintf("// Code generated by openapi-embed; DO NOT EDIT.\n// internal/api/openapi/openapi_spec_gen.go\npackage openapi\n\nvar OpenAPISpec = []byte(%s)\n", strconv.Quote(string(data)))

	if err := os.MkdirAll(filepath.Dir(*outputPath), 0o755); err != nil {
		fail("create output directory", err)
	}
	if err := os.WriteFile(*outputPath, []byte(content), 0o644); err != nil {
		fail("write generated OpenAPI asset", err)
	}
}

func fail(action string, err error) {
	fmt.Fprintf(os.Stderr, "failed to %s: %v\n", action, err)
	os.Exit(1)
}
