// cmd/openapi-embed/main.go
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
)

func main() {
	inputPath := flag.String("input", "dist/openapi.yaml", "path to the consumed OpenAPI bundle")
	outputPath := flag.String("output", "internal/openapispec/spec.gen.go", "path to the generated Go file")
	packageName := flag.String("package", "openapispec", "package name for the generated Go file")
	flag.Parse()

	data, err := os.ReadFile(*inputPath)
	if err != nil {
		fail("read bundled OpenAPI", err)
	}

	content := fmt.Sprintf(
		"// Code generated by openapi-embed; DO NOT EDIT.\npackage %s\n\nvar OpenAPISpec = []byte(%s)\n",
		*packageName,
		strconv.Quote(string(data)),
	)

	if err := os.MkdirAll(filepath.Dir(*outputPath), 0o755); err != nil {
		fail("create output directory", err)
	}
	if err := os.WriteFile(*outputPath, []byte(content), 0o644); err != nil {
		fail("write generated OpenAPI asset", err)
	}
}

func fail(action string, err error) {
	fmt.Fprintf(os.Stderr, "failed to %s: %v\n", action, err)
	os.Exit(1)
}
